import type { Metadata } from 'next'
import { inter, geistSans, geistMono } from '@/config/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App | Movies | Rent Movies',
  description:
    'Generated by create next app with Typescript and Tailwind CSS para rentar películas',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
