export const initialData = {
  movies: [
    {
      Title: 'Inception',
      Year: '2010',
      Rated: 'PG-13',
      Released: '16 Jul 2010',
      Runtime: '148 min',
      Genre: 'Action, Adventure, Sci-Fi',
      Director: 'Christopher Nolan',
      Writer: 'Christopher Nolan',
      Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
      Plot: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',
      Language: 'English, Japanese, French',
      Country: 'USA, UK',
      Awards: 'Won 4 Oscars. Another 152 wins & 204 nominations.',
      Poster: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8MVhGmwl4Rt4Ed70KEHS6o8xr7WBweI610g&s',
      Ratings: [
        { Source: 'Internet Movie Database', Value: '8.8/10' },
        { Source: 'Rotten Tomatoes', Value: '87%' },
      ],
      rentState: 'available',
    },
    {
      Title: 'Interstellar',
      Year: '2014',
      Rated: 'PG-13',
      Released: '07 Nov 2014',
      Runtime: '169 min',
      Genre: 'Adventure, Drama, Sci-Fi',
      Director: 'Christopher Nolan',
      Writer: 'Jonathan Nolan, Christopher Nolan',
      Actors: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
      Plot: "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
      Language: 'English',
      Country: 'USA, UK, Canada',
      Awards: 'Won 1 Oscar. Another 43 wins & 148 nominations.',
      Poster: 'https://example.com/interstellar.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.7/10' }],
      rentState: 'reserved',
    },
    {
      Title: 'The Matrix',
      Year: '1999',
      Rated: 'R',
      Released: '31 Mar 1999',
      Runtime: '136 min',
      Genre: 'Action, Sci-Fi',
      Director: 'Lana Wachowski, Lilly Wachowski',
      Writer: 'Lana Wachowski, Lilly Wachowski',
      Actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
      Plot: 'A hacker discovers the true nature of reality and his role in the war against its controllers.',
      Language: 'English',
      Country: 'USA',
      Awards: 'Won 4 Oscars. Another 42 wins & 51 nominations.',
      Poster: 'https://example.com/matrix.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.7/10' }],
      rentState: 'available',
    },
    {
      Title: 'The Dark Knight',
      Year: '2008',
      Rated: 'PG-13',
      Released: '18 Jul 2008',
      Runtime: '152 min',
      Genre: 'Action, Crime, Drama',
      Director: 'Christopher Nolan',
      Writer: 'Jonathan Nolan, Christopher Nolan',
      Actors: 'Christian Bale, Heath Ledger, Aaron Eckhart',
      Plot: 'Batman faces the Joker, a criminal mastermind who plunges Gotham City into chaos.',
      Language: 'English',
      Country: 'USA, UK',
      Awards: 'Won 2 Oscars. Another 157 wins & 163 nominations.',
      Poster: 'https://example.com/darkknight.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '9.0/10' }],
      rentState: 'unavailable',
    },
    {
      Title: 'Fight Club',
      Year: '1999',
      Rated: 'R',
      Released: '15 Oct 1999',
      Runtime: '139 min',
      Genre: 'Drama',
      Director: 'David Fincher',
      Writer: 'Jim Uhls, Chuck Palahniuk',
      Actors: 'Brad Pitt, Edward Norton, Helena Bonham Carter',
      Plot: 'An insomniac office worker forms an underground fight club that evolves into something much more.',
      Language: 'English',
      Country: 'USA, Germany',
      Awards: 'Nominated for 1 Oscar. 11 wins & 38 nominations.',
      Poster: 'https://example.com/fightclub.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }],
      rentState: 'available',
    },
    {
      Title: 'Forrest Gump',
      Year: '1994',
      Rated: 'PG-13',
      Released: '06 Jul 1994',
      Runtime: '142 min',
      Genre: 'Drama, Romance',
      Director: 'Robert Zemeckis',
      Writer: 'Winston Groom, Eric Roth',
      Actors: 'Tom Hanks, Robin Wright, Gary Sinise',
      Plot: 'The presidencies of Kennedy and Johnson, the Vietnam War, and more through the eyes of Forrest Gump.',
      Language: 'English',
      Country: 'USA',
      Awards: 'Won 6 Oscars. Another 50 wins & 75 nominations.',
      Poster: 'https://example.com/forrestgump.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }],
      rentState: 'reserved',
    },
    {
      Title: 'Gladiator',
      Year: '2000',
      Rated: 'R',
      Released: '05 May 2000',
      Runtime: '155 min',
      Genre: 'Action, Adventure, Drama',
      Director: 'Ridley Scott',
      Writer: 'David Franzoni, John Logan',
      Actors: 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
      Plot: 'A former Roman General seeks revenge against the corrupt emperor who murdered his family.',
      Language: 'English',
      Country: 'USA, UK',
      Awards: 'Won 5 Oscars. Another 59 wins & 104 nominations.',
      Poster: 'https://example.com/gladiator.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }],
      rentState: 'available',
    },
    {
      Title: 'The Shawshank Redemption',
      Year: '1994',
      Rated: 'R',
      Released: '14 Oct 1994',
      Runtime: '142 min',
      Genre: 'Drama',
      Director: 'Frank Darabont',
      Writer: 'Stephen King, Frank Darabont',
      Actors: 'Tim Robbins, Morgan Freeman',
      Plot: 'Two imprisoned men bond over years, finding solace and eventual redemption.',
      Language: 'English',
      Country: 'USA',
      Awards: 'Nominated for 7 Oscars. 21 wins & 43 nominations.',
      Poster: 'https://example.com/shawshank.jpg',
      Ratings: [{ Source: 'Internet Movie Database', Value: '9.3/10' }],
      rentState: 'unavailable',
    },
  ],
  categories: ['Acción y aventuras', 'Anime', 'Drama', 'Documental', 'Fantasía', 'Romance', 'Comedia', 'Horror','ninños', 'Ciencia ficción', 'Misterio', 'Thriller'],
}
